import tkinter as tk
import RPi.GPIO as GPIO
import time

GPIO.setmode(GPIO.BCM)
GPIO.setup(21,GPIO.OUT)
            
def laseron():
    GPIO.output(21,GPIO.LOW)
        
def laseroff():
    GPIO.output(21,GPIO.HIGH)
        
    
    
def laserslow():
    print("5")
    time.sleep(1)
    print("4")
    time.sleep(1)
    print("3")
    time.sleep(1)
    print("2")
    time.sleep(1)
    print("1")
    time.sleep(1)
    laseron()  
    time.sleep(0.88)
    laseroff()
    time.sleep(0.88)    
    laseron()
    time.sleep(0.88)
    laseroff()
    time.sleep(0.88)
    laseron()
    time.sleep(0.88)
    laseroff()
    time.sleep(0.88)
    laseron()
    time.sleep(0.88)
    laseroff()
    time.sleep(0.88)
    laseron()
    time.sleep(0.88)
    laseroff()
    time.sleep(0.88)
    laseron()
    time.sleep(0.88)
    laseroff()
    time.sleep(0.88)
    laseron()
    time.sleep(0.88)
    laseroff()
    time.sleep(0.88)
    laseron()
    time.sleep(0.88)
    laseroff()
    time.sleep(0.88)
    laseron()
    time.sleep(0.88)
    laseroff()
    time.sleep(0.88)
    laseron()
    time.sleep(0.88)
    laseroff()
    time.sleep(0.88)
    laseron()
    time.sleep(0.88)
    laseroff()
    time.sleep(0.88)
    laseron()
    time.sleep(0.88)
    laseroff()
    time.sleep(0.88)
    laseron()
    print("Laser Slow")


def laserfast():
    print("5")
    time.sleep(1)
    print("4")
    time.sleep(1)
    print("3")
    time.sleep(1)
    print("2")
    time.sleep(1)
    print("1")
    time.sleep(1)
    laseron()
    time.sleep(0.48)
    laseroff()
    time.sleep(0.48)    
    laseron()
    time.sleep(0.48)
    laseroff()
    time.sleep(0.48)
    laseron()
    time.sleep(0.48)
    laseroff()
    time.sleep(0.48)
    laseron()
    time.sleep(0.48)
    laseroff()
    time.sleep(0.48)
    laseron()
    time.sleep(0.48)
    laseroff()
    time.sleep(0.48)
    laseron()
    time.sleep(0.48)
    laseroff()
    time.sleep(0.48)
    laseron()
    time.sleep(0.48)
    laseroff()
    time.sleep(0.48)
    laseron()
    time.sleep(0.48)
    laseroff()
    time.sleep(0.48)
    laseron()
    time.sleep(0.48)
    laseroff()
    time.sleep(0.48)
    laseron()
    time.sleep(0.48)
    laseroff()
    time.sleep(0.48)
    laseron()
    time.sleep(0.48)
    laseroff()
    time.sleep(0.48)
    laseron()
    time.sleep(0.48)
    laseroff()
    time.sleep(0.48)
    laseron()
    time.sleep(0.48)
    laseroff()
    time.sleep(0.48)
    laseron()
    time.sleep(0.48)
    laseroff()
    time.sleep(0.48)
    laseron()
    time.sleep(0.48)
    laseroff()
    time.sleep(0.48)
    laseron()
    time.sleep(0.48)
    laseroff()
    time.sleep(0.48)
    laseron()
    time.sleep(0.48)
    laseroff()
    time.sleep(0.48)
    laseron()
    time.sleep(0.48)
    laseroff()
    time.sleep(0.48)
    laseron()
    time.sleep(0.48)
    laseroff()
    time.sleep(0.48)
    laseron()
    time.sleep(0.48)
    laseroff()
    time.sleep(0.48)
    laseron()
    time.sleep(0.48)
    laseroff()
    time.sleep(0.48)
    laseron()
    time.sleep(0.48)
    laseroff()
    time.sleep(0.48)
    laseron()
    time.sleep(0.48)
    laseroff()
    time.sleep(0.48)
    laseron()
    time.sleep(0.48)
    laseroff()
    time.sleep(0.48)
    laseron()
    time.sleep(0.48)
    laseroff()
    time.sleep(0.48)
    laseron()
    time.sleep(0.48)
    laseroff()
    time.sleep(0.48)
    laseron()
    time.sleep(0.48)
    laseroff()
    time.sleep(0.48)
    laseron()
    time.sleep(0.48)
    laseroff()
    time.sleep(0.48)
    laseron()
    time.sleep(0.48)
    laseroff()
    time.sleep(0.48)
    laseron()
    time.sleep(0.48)
    laseroff()
    time.sleep(0.48)
    laseron()
    time.sleep(0.48)
    laseroff()
    time.sleep(0.48)
    laseron()
    time.sleep(0.48)
    laseroff()
    time.sleep(0.48)
    laseron()
    print("Laser Fast")
  

main = tk.Tk()
main.title("Laser Control")

laseron_label = tk.Label(main, text = "Laser", foreground = "purple", font=("Helvetica",20))
laseron_button = tk.Button(main, text = "Laser On",command = laseron, background = "green", foreground = "white", font= ("Helvetica", 20))
laserdown_button = tk.Button(main, text = "Laser Off", command = laseroff, background = "red",foreground = "white", font=("Helvetica",20))
laserfast_button = tk.Button(main, text = "Laser Fast",command = laserfast, background = "cyan", foreground = "white", font= ("Helvetica", 20))
laserslow_button = tk.Button(main, text = "Laser Slow", command = laserslow, background = "blue", foreground = "white", font= ("Helvetica", 20))

laseron_label.grid(row = 0, column = 2)
laseron_button.grid(row = 1, column = 1)
laserdown_button.grid(row = 1, column = 3)
laserfast_button.grid(row = 2, column = 1)
laserslow_button.grid(row = 2, column = 3)

main.mainloop()
